Add range check for slotNumber in DSlotClickHandler#onSlotClick
(Hopefully) fixes this crash, which may have been caused by TrashSlot.

java.lang.IndexOutOfBoundsException: Index: 70, Size: 46
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
	at makamys.dmod.inventory.DSlotClickHandler.onSlotClick(DSlotClickHandler.java:31)
	at net.minecraft.inventory.Container.handler$preSlotClick$zbl000(SourceFile:617)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile)
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)